Logging: 
  IncludeScopes: false
  LogLevel: 
    Default: Debug
    System: Information
    Microsoft: Information

eureka:
  client:
    serviceUrl: http://localhost:8761/eureka/

zipkin:
  url: http://localhost:9411